version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.33.5

    ports:
      - 9090:9090

    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
